// Directory packs are the install path that needs no rebuild: one
// subdirectory per pack, each with a manifest and a checksum.
//
// The on-disk unit is deliberate. A single JSON file per pack would have been
// the smallest change, and it is what Decode takes — but IconAsset already
// carries bytes no author wants to base64 into JSON by hand, and the WASM
// packs of FEAT-48hreg reuse this loader by adding a module kind beside the
// manifest rather than a second loader. So a pack is a directory:
//
//	<packs dir>/<name>/pack.json    the manifest Decode reads
//	<packs dir>/<name>/pack.sha256  the hex SHA-256 of pack.json
//
// The checksum is a lockfile-style record, not ceremony. These files become
// node definitions with outbound HTTP routing and credential bindings, and a
// mutable directory on a server is a place where a file can change without
// anyone deciding it should. The sidecar is generated by the operator —
// `sha256sum pack.json` — so the check is against something a human approved
// rather than against the file's own claim about itself. A pack without one,
// or one whose bytes no longer match, is refused rather than loaded.
//
// Any failure names the pack and the reason and aborts the boot: a pack that
// silently failed to register would leave workflows referencing a node type
// that can never activate, and an operator looking at a running server would
// not think to check the logs. An absent or empty directory is the normal
// silent condition, so the default deployment is unchanged.
package nodepack

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kilaslab/kilas-flow/internal/loadoptions"
	"github.com/kilaslab/kilas-flow/internal/node"
	"github.com/kilaslab/kilas-flow/internal/routing"
	"github.com/kilaslab/kilas-flow/internal/webhook"
)

// ManifestName is the file each pack directory carries that Decode reads.
const ManifestName = "pack.json"

// ChecksumName is the sidecar holding the hex SHA-256 of the manifest.
//
// Compatible with `sha256sum pack.json`: the first whitespace-delimited field
// is the digest and anything after it is ignored, so both bare digests and
// `sha256sum` output verify.
const ChecksumName = "pack.sha256"

// DirDeps is everything a directory-loaded pack registers into.
//
// Grouped rather than passed as seven parameters because the point is that
// they arrive together: a definition without its routing, its event table,
// its delivery shape or its lifecycle hook is a node that registers cleanly
// and fails later. It mirrors what the embedded WAHA pack takes, so a pack
// loaded from disk registers exactly what the same bytes embedded register.
type DirDeps struct {
	Definitions *node.Registry
	Routes      *routing.Registry
	Triggers    *TriggerRegistry
	Deliveries  *webhook.Registry
	Lifecycles  *webhook.LifecycleRegistry
	Executors   ExecutorSet
	Options     *loadoptions.Resolver
}

// LoadDir installs every pack found in dir, at composition, before the
// registry is shared.
//
// An empty dir and an absent one are both silent no-ops. Anything else that
// goes wrong — an unreadable manifest, a missing or mismatched checksum, a
// malformed pack, a duplicate registration — is an error naming the pack,
// and the caller refuses to start on it rather than serving a half-registered
// catalogue.
func LoadDir(deps DirDeps, dir string) error {
	if strings.TrimSpace(dir) == "" {
		return nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("list node packs in %q: %w", dir, err)
	}
	// ReadDir sorts by filename, which is what makes a duplicate registration
	// report the same pack on every boot rather than whichever the filesystem
	// returned first.
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if err := loadPackDir(deps, dir, entry.Name()); err != nil {
			return err
		}
	}
	return nil
}

// loadPackDir installs the one pack living in dir/name.
func loadPackDir(deps DirDeps, dir, name string) error {
	manifestPath := filepath.Join(dir, name, ManifestName)
	manifest, err := os.ReadFile(manifestPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("load node pack %q: %s is missing", name, ManifestName)
		}
		return fmt.Errorf("load node pack %q: read %s: %w", name, manifestPath, err)
	}
	if err := checkPackDigest(dir, name, manifest); err != nil {
		return err
	}
	pack, err := Decode(manifest)
	if err != nil {
		return fmt.Errorf("load node pack %q: %s: %w", name, manifestPath, err)
	}
	if err := Register(deps.Definitions, deps.Routes, deps.Executors, deps.Options, pack); err != nil {
		return fmt.Errorf("load node pack %q: %w", name, err)
	}
	if pack.Trigger == nil {
		return nil
	}
	if err := RegisterTrigger(deps.Triggers, deps.Deliveries, deps.Lifecycles, pack); err != nil {
		return fmt.Errorf("load node pack %q: %w", name, err)
	}
	return nil
}

// checkPackDigest refuses a manifest whose bytes no longer match the digest
// the operator approved in the sidecar.
func checkPackDigest(dir, name string, manifest []byte) error {
	checksumPath := filepath.Join(dir, name, ChecksumName)
	recorded, err := os.ReadFile(checksumPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("load node pack %q: %s is missing: generate it with `sha256sum pack.json`", name, ChecksumName)
		}
		return fmt.Errorf("load node pack %q: read %s: %w", name, checksumPath, err)
	}
	fields := strings.Fields(string(recorded))
	if len(fields) == 0 {
		return fmt.Errorf("load node pack %q: %s holds no digest", name, ChecksumName)
	}
	want, err := hex.DecodeString(fields[0])
	if err != nil || len(want) != sha256.Size {
		return fmt.Errorf("load node pack %q: %s is not a SHA-256 hex digest", name, ChecksumName)
	}
	if sum := sha256.Sum256(manifest); string(sum[:]) != string(want) {
		return fmt.Errorf("load node pack %q: %s no longer matches its recorded digest: regenerate it or restore the approved manifest",
			name, ManifestName)
	}
	return nil
}
