// Package abigen renders the guest's wasip1 bindings from the ABI table.
//
// The table in pkg/sdk is the definition; this turns it into the import
// declarations a wasip1 module needs. It exists so the two sides cannot drift:
// a row added to sdk.Functions without regenerating is caught by
// TestGeneratedGuestBindingsAreCurrent, and a hand-edited binding is caught by
// the same test because the file it compares against is what this renders.
package abigen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	sdk "github.com/kilaslab/kilas-flow/pkg/sdk"
)

// Render returns the generated bindings for functions, gofmt'd.
//
// The output declares one body-less function per row, each carrying the
// //go:wasmimport directive that binds it to sdk.HostModule. There are no
// adapters here: turning a byte slice into a pointer and a length is the
// pointer convention's job and lives in guest_wasip1.go, so this file is only
// ever the shape of the ABI.
func Render(functions []sdk.Function) ([]byte, error) {
	if sdk.HostModule == "" {
		return nil, fmt.Errorf("abigen: the ABI names no host module")
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by internal/abigen from abi.go. DO NOT EDIT.\n\n")
	source.WriteString("//go:build wasip1\n\n")
	source.WriteString("package sdk\n\n")
	source.WriteString("// The host functions a pack may import, generated from Functions in abi.go.\n")
	source.WriteString("//\n")
	source.WriteString("// Each is a declaration, not an implementation: the body is the host's, and a\n")
	source.WriteString("// call this module never reaches is dropped by the linker together with its\n")
	source.WriteString("// import, which is what keeps a capability-free pack import-free.\n")
	for _, function := range functions {
		if function.Name == "" {
			return nil, fmt.Errorf("abigen: a function in the ABI table has no name")
		}
		if len(function.Params) == 0 {
			return nil, fmt.Errorf("abigen: %s has no parameters, so it is not an ABI v1 function", function.Name)
		}
		if function.Doc != "" {
			fmt.Fprintf(&source, "\n// %s\n", function.Doc)
		}
		fmt.Fprintf(&source, "//\n//go:wasmimport %s %s\n", sdk.HostModule, function.Name)
		params := make([]string, len(function.Params))
		for index, name := range function.Params {
			params[index] = name + " uint32"
		}
		fmt.Fprintf(&source, "func host%s(%s) int32\n", goName(function.Name), strings.Join(params, ", "))
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("abigen: the generated source does not parse: %w", err)
	}
	return formatted, nil
}

// initialisms are the segments a binding's Go name spells in capitals, so
// http_request becomes hostHTTPRequest rather than hostHttpRequest.
var initialisms = map[string]string{"http": "HTTP"}

// goName renders an ABI function name as the Go name its binding is declared
// with: every underscore-separated segment capitalised, with the initialisms
// above respected.
func goName(name string) string {
	segments := strings.Split(name, "_")
	var rendered strings.Builder
	for _, segment := range segments {
		if upper, ok := initialisms[segment]; ok {
			rendered.WriteString(upper)
			continue
		}
		if segment == "" {
			continue
		}
		rendered.WriteString(strings.ToUpper(segment[:1]))
		rendered.WriteString(segment[1:])
	}
	return rendered.String()
}
