// Code generated by internal/abigen from abi.go. DO NOT EDIT.

//go:build wasip1

package sdk

// The host functions a pack may import, generated from Functions in abi.go.
//
// Each is a declaration, not an implementation: the body is the host's, and a
// call this module never reaches is dropped by the linker together with its
// import, which is what keeps a capability-free pack import-free.

// sends one HTTP request and writes the response head and body into the result slots
//
//go:wasmimport kilasflow_v1 http_request
func hostHTTPRequest(meta_ptr uint32, meta_len uint32, body_ptr uint32, body_len uint32) int32

// reads one non-secret field of a credential the node attached
//
//go:wasmimport kilasflow_v1 credential_field
func hostCredentialField(type_ptr uint32, type_len uint32, field_ptr uint32, field_len uint32) int32

// reads a payload the input items carry or this run wrote
//
//go:wasmimport kilasflow_v1 binary_read
func hostBinaryRead(id_ptr uint32, id_len uint32) int32

// stores a payload and writes its reference into the result slot
//
//go:wasmimport kilasflow_v1 binary_write
func hostBinaryWrite(meta_ptr uint32, meta_len uint32, data_ptr uint32, data_len uint32) int32

// reports how many bytes a result slot holds
//
//go:wasmimport kilasflow_v1 result_len
func hostResultLen(slot uint32) int32

// copies bytes out of a result slot into the guest's memory
//
//go:wasmimport kilasflow_v1 result_read
func hostResultRead(slot uint32, offset uint32, dst_ptr uint32, dst_cap uint32) int32
